package models

type BusinessInvoiceSettings struct {
	ID                            string `json:"id"`
	BusinessID                    string `json:"businessId"`
	Name                          string `json:"name"`
	Code                          string `json:"code"`
	ProductLabel                  string `json:"productLabel"`
	QuantityLabel                 string `json:"quantityLabel"`
	UnitPriceLabel                string `json:"unitPriceLabel"`
	SubTotalLabel                 string `json:"subTotalLabel"`
	CategoryHsnCodeLabel          string `json:"categoryHsnCodeLabel"`
	TotalQuantityLabel            string `json:"totalQuantityLabel"`
	ItemDiscountLabel             string `json:"itemDiscountLabel"`
	DiscountedUnitPriceLabel      string `json:"discountedUnitPriceLabel"`
	SubheadingLine1               string `json:"subheadingLine1"`
	SubheadingLine2               string `json:"subheadingLine2"`
	SubheadingLine3               string `json:"subheadingLine3"`
	SubheadingLine4               string `json:"subheadingLine4"`
	SubheadingLine5               string `json:"subheadingLine5"`
	Design                        string `json:"design"`
	PaperSize                     string `json:"paperSize"`
	IsDefault                     bool   `json:"isDefault"`
	ShowLogo                      bool   `json:"showLogo"`
	ShowBusinessDetails           bool   `json:"showBusinessDetails"`
	ShowCustomerDetails           bool   `json:"showCustomerDetails"`
	ShowItemsSku                  bool   `json:"showItemsSku"`
	ShowBrand                     bool   `json:"showBrand"`
	ShowSaleDescription           bool   `json:"showSaleDescription"`
	ShowQrCode                    bool   `json:"showQrCode"`
	ShowProductExpiry             bool   `json:"showProductExpiry"`
	ShowLotNumber                 bool   `json:"showLotNumber"`
	ShowProductImage              bool   `json:"showProductImage"`
	ShowWarrantyName              bool   `json:"showWarrantyName"`
	ShowWarrantyExpiryDate        bool   `json:"showWarrantyExpiryDate"`
	ShowWarrantyDescription       bool   `json:"showWarrantyDescription"`
	ShowTaxBreakdown              bool   `json:"showTaxBreakdown"`
	ShowDiscounts                 bool   `json:"showDiscounts"`
	ShowBarcode                   bool   `json:"showBarcode"`
	BarcodeTotalDueLabel          string `json:"barcodeTotalDueLabel"`
	ShowTotalBalanceDue           bool   `json:"showTotalBalanceDue"`
	BarcodeChangeReturnLabel      string `json:"barcodeChangeReturnLabel"`
	HideAllPrices                 bool   `json:"hideAllPrices"`
	ShowTotalInWords              bool   `json:"showTotalInWords"`
	BarcodeWordFormat             string `json:"barcodeWordFormat"`
	BarcodeTaxSummaryLabel        string `json:"barcodeTaxSummaryLabel"`
	HeaderAlignment               string `json:"headerAlignment"`
	LogoURL                       string `json:"logoUrl"`
	QrShowLabels                  bool   `json:"qrShowLabels"`
	QrShowBusinessName            bool   `json:"qrShowBusinessName"`
	QrShowBusinessLocationAddress bool   `json:"qrShowBusinessLocationAddress"`
	QrShowInvoiceNo               bool   `json:"qrShowInvoiceNo"`
	QrShowSubtotal                bool   `json:"qrShowSubtotal"`
	QrShowTotalAmountWithTax      bool   `json:"qrShowTotalAmountWithTax"`
	QrShowTotalTax                bool   `json:"qrShowTotalTax"`
	QrShowCustomerName            bool   `json:"qrShowCustomerName"`
	QrShowInvoiceUrl              bool   `json:"qrShowInvoiceUrl"`
	QrShowInvoiceDateTime         bool   `json:"qrShowInvoiceDateTime"`
	QrShowBusinessTax1            bool   `json:"qrShowBusinessTax1"`
	InvoiceNote                   string `json:"invoiceNote"`
	CreatedAt                     string `json:"createdAt"`
	UpdatedAt                     string `json:"updatedAt"`
}
