ALTER TABLE notifications
ADD COLUMN IF NOT EXISTS email_subject TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS email_cc TEXT[] NOT NULL DEFAULT ARRAY[]::text[],
ADD COLUMN IF NOT EXISTS email_bcc TEXT[] NOT NULL DEFAULT ARRAY[]::text[];
