CREATE TABLE IF NOT EXISTS business_invoice_settings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(255) NOT NULL,
    product_label VARCHAR(255) NOT NULL DEFAULT 'Product',
    quantity_label VARCHAR(100) NOT NULL DEFAULT 'Qty',
    unit_price_label VARCHAR(255) NOT NULL DEFAULT 'Unit Price',
    sub_total_label VARCHAR(255) NOT NULL DEFAULT 'Subtotal',
    category_hsn_code_label VARCHAR(255) NOT NULL DEFAULT 'Category / HSN Code',
    total_quantity_label VARCHAR(255) NOT NULL DEFAULT 'Total Quantity',
    item_discount_label VARCHAR(255) NOT NULL DEFAULT 'Item Discount',
    discounted_unit_price_label VARCHAR(255) NOT NULL DEFAULT 'Discounted Unit Price',
    subheading_line_1 TEXT NOT NULL DEFAULT '',
    subheading_line_2 TEXT NOT NULL DEFAULT '',
    subheading_line_3 TEXT NOT NULL DEFAULT '',
    subheading_line_4 TEXT NOT NULL DEFAULT '',
    subheading_line_5 TEXT NOT NULL DEFAULT '',
    design VARCHAR(50) NOT NULL DEFAULT 'classic',
    paper_size VARCHAR(20) NOT NULL DEFAULT 'a4',
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    show_logo BOOLEAN NOT NULL DEFAULT TRUE,
    show_business_details BOOLEAN NOT NULL DEFAULT TRUE,
    show_customer_details BOOLEAN NOT NULL DEFAULT TRUE,
    show_items_sku BOOLEAN NOT NULL DEFAULT TRUE,
    show_brand BOOLEAN NOT NULL DEFAULT TRUE,
    show_sale_description BOOLEAN NOT NULL DEFAULT TRUE,
    show_qr_code BOOLEAN NOT NULL DEFAULT FALSE,
    show_product_expiry BOOLEAN NOT NULL DEFAULT TRUE,
    show_lot_number BOOLEAN NOT NULL DEFAULT TRUE,
    show_product_image BOOLEAN NOT NULL DEFAULT TRUE,
    show_warranty_name BOOLEAN NOT NULL DEFAULT TRUE,
    show_warranty_expiry_date BOOLEAN NOT NULL DEFAULT TRUE,
    show_warranty_description BOOLEAN NOT NULL DEFAULT TRUE,
    show_tax_breakdown BOOLEAN NOT NULL DEFAULT TRUE,
    show_discounts BOOLEAN NOT NULL DEFAULT TRUE,
    show_barcode BOOLEAN NOT NULL DEFAULT TRUE,
    barcode_total_due_label VARCHAR(255) NOT NULL DEFAULT 'Due',
    show_total_balance_due BOOLEAN NOT NULL DEFAULT TRUE,
    barcode_change_return_label VARCHAR(255) NOT NULL DEFAULT 'Change return label',
    hide_all_prices BOOLEAN NOT NULL DEFAULT FALSE,
    show_total_in_words BOOLEAN NOT NULL DEFAULT TRUE,
    barcode_word_format VARCHAR(20) NOT NULL DEFAULT 'international',
    barcode_tax_summary_label VARCHAR(255) NOT NULL DEFAULT 'Tax summary label',
    header_alignment VARCHAR(20) NOT NULL DEFAULT 'center',
    logo_url TEXT NOT NULL DEFAULT '',
    qr_show_labels BOOLEAN NOT NULL DEFAULT TRUE,
    qr_show_business_name BOOLEAN NOT NULL DEFAULT TRUE,
    qr_show_business_location_address BOOLEAN NOT NULL DEFAULT TRUE,
    qr_show_invoice_no BOOLEAN NOT NULL DEFAULT TRUE,
    qr_show_subtotal BOOLEAN NOT NULL DEFAULT TRUE,
    qr_show_total_amount_with_tax BOOLEAN NOT NULL DEFAULT TRUE,
    qr_show_total_tax BOOLEAN NOT NULL DEFAULT TRUE,
    qr_show_customer_name BOOLEAN NOT NULL DEFAULT TRUE,
    qr_show_invoice_url BOOLEAN NOT NULL DEFAULT TRUE,
    qr_show_invoice_date_time BOOLEAN NOT NULL DEFAULT TRUE,
    qr_show_business_tax1 BOOLEAN NOT NULL DEFAULT TRUE,
    invoice_note TEXT NOT NULL DEFAULT 'Thank you for your business.',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS business_invoice_settings_business_code_unique
    ON business_invoice_settings (business_id, code);

CREATE UNIQUE INDEX IF NOT EXISTS business_invoice_settings_one_default_per_business
    ON business_invoice_settings (business_id)
    WHERE is_default;
